name: .NET Develop

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Package
      run: dotnet pack --no-build src/Adeotek.SqlDependencyListener.csproj --output .
    - uses: bbonkr/get-version-action@v1.0.4
      id: get_version
      with:
        project: "src/Adeotek.SqlDependencyListener.csproj"
    - name: logging
      run: |
        echo "Version=${{ steps.get_version.outputs.version }}"
